package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log"
	"net/http"
	"strings"
	"time"

	"github.com/infostellarinc/stellarstation-cli/internal/auth"
)

// AuthorizerCredentials contains temporary AWS credentials and configuration from the authorizer
type AuthorizerCredentials struct {
	// AWS credentials for S3 access (STS assumed-role credentials)
	AccessKeyID     string `json:"accessKeyId"`
	SecretAccessKey string `json:"secretAccessKey"`
	//nolint:gosec // G117: SessionToken is intentionally a secret field in credentials struct
	SessionToken string    `json:"sessionToken"`
	Expiration   time.Time `json:"expiration"`

	// S3 configuration
	S3Bucket    string `json:"s3Bucket"`
	S3Region    string `json:"s3Region"`
	Environment string `json:"environment"`

	// IoT/MQTT configuration (only if MQTT features requested)
	ClientID string `json:"clientId"`

	// Stream ID - unique identifier for this stream instance (generated by authorizer)
	StreamID string `json:"streamId,omitempty"`

	// PassID is the plan/pass the authorizer resolved the stream against. When the
	// request supplied only satelliteId, this is the next upcoming plan the
	// authorizer selected.
	PassID string `json:"passId,omitempty"`

	// X.509 certificate for MQTT over mutual TLS (port 8883).
	// IoTCertEndpoint is the iot:Data-ATS hostname to connect to on port 8883.
	IoTCertificatePem string `json:"iotCertificatePem,omitempty"`
	IoTPrivateKeyPem  string `json:"iotPrivateKeyPem,omitempty"`
	IoTCertificateID  string `json:"iotCertificateId,omitempty"`
	IoTCertEndpoint   string `json:"iotCertEndpoint,omitempty"`

	// Streams - each enabled feature gets its S3 path and MQTT topic
	Streams StreamsConfig `json:"streams"`

	// Channels describes each channel's data type (rate class, direction,
	// transport, framings), resolved from the pass execution configuration.
	// Populated when the request omits channelIds, so the CLI can stream all
	// channels by default and label each by data type.
	Channels []ChannelMetadata `json:"channels,omitempty"`

	// Diagnostics configuration - where to upload diagnostics files
	DiagnosticsBucket string `json:"diagnosticsBucket,omitempty"` // S3 bucket for diagnostics (defaults to S3Bucket)
	DiagnosticsPrefix string `json:"diagnosticsPrefix"`           // S3 prefix for diagnostics files
}

// ChannelMetadata describes one channel's data type as resolved from the pass
// execution configuration. Rate class decides how the CLI consumes the channel:
// low_rate over MQTT, high_rate direct from S3.
type ChannelMetadata struct {
	ChannelID string   `json:"channelId"`
	Direction string   `json:"direction,omitempty"` // "uplink" | "downlink"
	RateClass string   `json:"rateClass,omitempty"` // "low_rate" | "high_rate"
	Transport string   `json:"transport,omitempty"` // "mqtt" | "s3"
	Framings  []string `json:"framings,omitempty"`  // declared framing(s)
}

// Rate class / direction constants for channel metadata classification.
const (
	rateClassLowRate  = "low_rate"
	rateClassHighRate = "high_rate"
	directionDownlink = "downlink"
	directionUplink   = "uplink"
)

// HighRateChannelIDs returns the downlink channel IDs whose rate class is
// high_rate (consumed directly from S3 rather than MQTT).
func (c *AuthorizerCredentials) HighRateChannelIDs() []string {
	if c == nil {
		return nil
	}
	var out []string
	for _, ch := range c.Channels {
		if ch.RateClass == rateClassHighRate {
			out = append(out, ch.ChannelID)
		}
	}
	return out
}

// logChannelClassification prints a concise summary of the resolved channels
// grouped by data type (low-rate MQTT, high-rate S3, uplink), with each channel's
// declared framings, so the operator can see which channel carries what.
func logChannelClassification(channels []ChannelMetadata) {
	if len(channels) == 0 {
		return
	}
	var low, high, uplink []string
	label := func(ch ChannelMetadata) string {
		if len(ch.Framings) > 0 {
			return fmt.Sprintf("%s [%s]", ch.ChannelID, strings.Join(ch.Framings, ","))
		}
		return ch.ChannelID
	}
	for _, ch := range channels {
		switch {
		case ch.Direction == directionUplink:
			// Uplink is command-only; framing does not apply.
			uplink = append(uplink, ch.ChannelID)
		case ch.RateClass == rateClassHighRate:
			high = append(high, label(ch))
		default:
			low = append(low, label(ch))
		}
	}
	log.Printf("Channels (from execution config): %d low-rate over MQTT, %d high-rate from S3, %d uplink",
		len(low), len(high), len(uplink))
	if len(low) > 0 {
		log.Printf("  low-rate (MQTT):  %s", strings.Join(low, ", "))
	}
	if len(high) > 0 {
		log.Printf("  high-rate (S3):   %s", strings.Join(high, ", "))
	}
	if len(uplink) > 0 {
		log.Printf("  uplink:           %s", strings.Join(uplink, ", "))
	}
}

// StreamsConfig contains configuration for each data stream type
// Only populated for features that were requested
type StreamsConfig struct {
	HighRate      *StreamConfig   `json:"highRate,omitempty"`
	LowRate       []StreamConfig  `json:"lowRate,omitempty"` // One per channel
	Monitoring    *StreamConfig   `json:"monitoring,omitempty"`
	Config        *StreamConfig   `json:"config,omitempty"`
	Event         *StreamConfig   `json:"event,omitempty"`
	Uplink        []CommandConfig `json:"uplink,omitempty"`        // Publish topic + ack subscribe (one per channel)
	ConfigRequest []CommandConfig `json:"configRequest,omitempty"` // Publish topic + ack subscribe (one per channel)
}

// StreamConfig contains S3 path and MQTT topic for a data stream
type StreamConfig struct {
	S3Prefix  string `json:"s3Prefix"`            // S3 prefix to read from
	MqttTopic string `json:"mqttTopic,omitempty"` // MQTT topic to subscribe to (if applicable)
}

// CommandConfig contains publish topic and ack subscription for commands
type CommandConfig struct {
	PublishTopic string `json:"publishTopic"` // MQTT topic to publish commands to
	AckTopic     string `json:"ackTopic"`     // MQTT topic to subscribe for acks
	S3AckPrefix  string `json:"s3AckPrefix"`  // S3 prefix for ack backups
}

// AuthorizerRequest contains the parameters sent to the authorizer API
type AuthorizerRequest struct {
	PassID string `json:"passId"`
	// SatelliteID requests the authorizer default to the next upcoming plan for
	// this satellite when PassID is empty. Ignored when PassID is set.
	SatelliteID string   `json:"satelliteId,omitempty"`
	ChannelIDs  []string `json:"channelIds"`
	Environment string   `json:"environment,omitempty"`
	Region      string   `json:"region,omitempty"`
	Source      string   `json:"source,omitempty"` // identifies which client the stream belongs to; the CLI sends "streamer"

	// ClientVersion is this client's release version. The authorizer records it
	// on the stream, so the pass monitoring page shows which client version
	// opened each stream.
	ClientVersion string `json:"clientVersion,omitempty"`

	// StreamID, when set, asks the authorizer to reuse an existing stream (and its
	// commanding authority) instead of opening a new one; used by credential
	// refreshes so they don't collide with this stream's own commanding lock.
	StreamID string `json:"streamId,omitempty"`

	// Feature flags - tell authorizer what streams we need access to
	EnableDownlink       bool `json:"enableDownlink,omitempty"`
	EnableMonitoring     bool `json:"enableMonitoring,omitempty"`
	EnableConfigState    bool `json:"enableConfigState,omitempty"`
	EnableEvent          bool `json:"enableEvent,omitempty"`
	EnableUplink         bool `json:"enableUplink,omitempty"`
	EnableConfigRequests bool `json:"enableConfigRequests,omitempty"`

	// OverrideCommandingLock asks the authorizer to allow this uplink stream even
	// if another client already holds commanding authority on a requested channel
	// (the one-commanding-authority-per-channel rule). Set from --override-commanding-lock.
	OverrideCommandingLock bool `json:"overrideCommandingLock,omitempty"`
}

// fetchAuthorizerCredentials calls the authorizer API to get temporary AWS credentials
// and stream configuration (S3 paths, MQTT topics) for the requested features.
// Retries on 5xx errors to ride out transient server errors (e.g., 503 Service Unavailable).
// A nil tokenSource is allowed for unauthenticated smoke tests but will cause the authorizer to return 401.
func fetchAuthorizerCredentials(
	ctx context.Context,
	apiURL string,
	tokenSource auth.TokenSource,
	authReq AuthorizerRequest,
) (*AuthorizerCredentials, error) {
	bodyJSON, err := json.Marshal(authReq)
	if err != nil {
		return nil, fmt.Errorf("marshal request: %w", err)
	}

	client := &http.Client{Timeout: authorizerClientTimeout}

	vlogf(
		"fetching authorizer credentials: url=%s passId=%s channels=%v downlink=%v monitoring=%v config=%v event=%v uplink=%v configRequest=%v",
		apiURL,
		authReq.PassID,
		authReq.ChannelIDs,
		authReq.EnableDownlink,
		authReq.EnableMonitoring,
		authReq.EnableConfigState,
		authReq.EnableEvent,
		authReq.EnableUplink,
		authReq.EnableConfigRequests,
	)

	for attempt := 0; attempt < authorizerMaxRetries; attempt++ {
		// Create a new request for each attempt since the body reader is consumed
		req, err := http.NewRequestWithContext(
			ctx,
			http.MethodPost,
			apiURL,
			bytes.NewReader(bodyJSON),
		)
		if err != nil {
			return nil, fmt.Errorf("create request: %w", err)
		}
		req.Header.Set("Content-Type", "application/json")
		if tokenSource != nil {
			token, tokErr := tokenSource.Token(ctx)
			if tokErr != nil {
				return nil, fmt.Errorf("obtain access token: %w", tokErr)
			}
			if token != "" {
				req.Header.Set("Authorization", "Bearer "+token)
			}
		}

		//nolint:gosec // G704: apiURL is from trusted flag/environment variable
		resp, err := client.Do(req)
		if err != nil {
			return nil, fmt.Errorf("API request failed: %w", err)
		}

		// Check for 5xx errors that should be retried (especially 503 Service Unavailable)
		if resp.StatusCode >= 500 && resp.StatusCode < 600 {
			body, _ := io.ReadAll(resp.Body)
			_ = resp.Body.Close()

			// Check if we should retry
			if attempt < authorizerMaxRetries-1 {
				backoff := authorizerRetryInitialBackoff * time.Duration(1<<uint(attempt))
				if backoff > authorizerRetryMaxBackoff {
					backoff = authorizerRetryMaxBackoff
				}

				vlogf(
					"authorizer returned %d, retrying in %v (attempt %d/%d): %s",
					resp.StatusCode,
					backoff,
					attempt+1,
					authorizerMaxRetries,
					string(body),
				)

				// Wait before retrying, respecting context cancellation
				select {
				case <-ctx.Done():
					return nil, fmt.Errorf("context cancelled while retrying authorizer request: %w", ctx.Err())
				case <-time.After(backoff):
					// Continue to next retry
				}
				continue
			}

			// All retries exhausted
			var errorResp struct {
				Error   string `json:"error"`
				Message string `json:"message"`
			}
			if err := json.Unmarshal(body, &errorResp); err == nil {
				return nil, fmt.Errorf(
					"authorizer returned status %d after %d attempts: %s - %s",
					resp.StatusCode,
					authorizerMaxRetries,
					errorResp.Error,
					errorResp.Message,
				)
			}
			return nil, fmt.Errorf(
				"authorizer returned status %d after %d attempts: %s",
				resp.StatusCode,
				authorizerMaxRetries,
				string(body),
			)
		}

		// Handle non-5xx errors (4xx, etc.) - don't retry these
		if resp.StatusCode != http.StatusOK {
			body, _ := io.ReadAll(resp.Body)
			_ = resp.Body.Close()

			var errorResp struct {
				Error   string `json:"error"`
				Message string `json:"message"`
			}
			if err := json.Unmarshal(body, &errorResp); err == nil {
				detail := errorResp.Message
				if detail == "" {
					detail = errorResp.Error
				}
				if detail != "" {
					return nil, fmt.Errorf("%s (status %d)", detail, resp.StatusCode)
				}
			}
			return nil, fmt.Errorf("the request was rejected (status %d): %s", resp.StatusCode, string(body))
		}

		// Success - decode the response
		var creds AuthorizerCredentials
		if err := json.NewDecoder(resp.Body).Decode(&creds); err != nil {
			_ = resp.Body.Close()
			return nil, fmt.Errorf("decode response: %w", err)
		}
		_ = resp.Body.Close()

		if creds.AccessKeyID == "" || creds.SecretAccessKey == "" || creds.SessionToken == "" {
			return nil, errors.New("authorizer response missing credentials")
		}

		if attempt > 0 {
			vlogf("authorizer credentials received after %d retries", attempt+1)
		}

		vlogf(
			"authorizer credentials received: expiration=%s bucket=%s region=%s clientId=%s certEndpoint=%s certId=%s streams(highRate=%v lowRate=%d monitoring=%v config=%v event=%v uplink=%v configRequest=%v)",
			creds.Expiration.Format(time.RFC3339),
			creds.S3Bucket,
			creds.S3Region,
			creds.ClientID,
			creds.IoTCertEndpoint,
			creds.IoTCertificateID,
			creds.Streams.HighRate != nil,
			len(creds.Streams.LowRate),
			creds.Streams.Monitoring != nil,
			creds.Streams.Config != nil,
			creds.Streams.Event != nil,
			len(creds.Streams.Uplink) > 0,
			len(creds.Streams.ConfigRequest) > 0,
		)

		return &creds, nil
	}

	// This should never be reached (loop always returns or continues)
	return nil, fmt.Errorf("authorizer request failed after %d attempts", authorizerMaxRetries)
}

// collectChannelIDsFromAuthorizerStreams derives channel UUIDs from the authorizer streams
// payload so the CLI can run S3 high-rate readers and stats when -channels was omitted
// (authorizer resolves channels from the pass execution configuration).
func collectChannelIDsFromAuthorizerStreams(streams StreamsConfig) []string {
	seen := make(map[string]struct{})
	var out []string
	add := func(id string) {
		if id == "" {
			return
		}
		if _, ok := seen[id]; ok {
			return
		}
		seen[id] = struct{}{}
		out = append(out, id)
	}
	for _, lr := range streams.LowRate {
		if strings.Contains(lr.MqttTopic, "/downlink") {
			add(ExtractChannelIDFromTopic(lr.MqttTopic))
		}
	}
	for _, u := range streams.Uplink {
		add(ExtractChannelIDFromTopic(u.PublishTopic))
	}
	for _, c := range streams.ConfigRequest {
		add(ExtractChannelIDFromTopic(c.PublishTopic))
	}
	return out
}
